# Generated by Django 5.2.4 on 2025-07-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'BuildingRecord',
                'verbose_name_plural': 'BuildingRecords',
            },
        ),
        migrations.CreateModel(
            name='FloorRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='data.buildingrecords')),
            ],
            options={
                'verbose_name': 'FloorRecord',
                'verbose_name_plural': 'FloorRecords',
            },
        ),
        migrations.CreateModel(
            name='NurseRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'NurseRecord',
                'verbose_name_plural': 'NurseRecords',
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoomRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='data.floorrecords')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='data.nurserecords')),
            ],
            options={
                'verbose_name': 'RoomRecord',
                'verbose_name_plural': 'RoomRecords',
            },
        ),
        migrations.CreateModel(
            name='BedRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('blockec', 'Blocked'), ('occupied_male', 'Occupied (Male)'), ('occupied_female', 'Occupied (Female)'), ('occupied_discharge', 'Occupied Discharge'), ('vacant_dirty', 'Vacant Dirty'), ('nan', 'NaN')], default='nan', max_length=255, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='data.roomrecords')),
            ],
            options={
                'verbose_name': 'BedRecord',
                'verbose_name_plural': 'BedRecords',
            },
        ),
    ]
